[project]
name = "district-heating-multihop-sim"
version = "0.1.0"
description = "Discrete-event simulation of LoRa multihop scheme for district heating grids"
readme = "README.md"
authors = [
    { name = "CKjaer", email = "christankjaernielsen@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
    "seaborn>=0.13.2",
]

[project.scripts]
district-heating-multihop-sim-relay = "district-heating-multihop-sim:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.4",
]
